export const API_KEY = 'AIzaSyC8o7aoZ3xtpMqOaJrzXhHVPDxfqM-PeHw';
export const BASE_URL = 'https://www.googleapis.com/youtube/v3';

export const COLORS = {
    primary: '#ff0000',
    secondary: '#282828',
    white: '#ffffff',
    black: '#0f0f0f',
    gray: '#AAAAAA',
    lightGray: '#F1F1F1',
    darkGray: '#606060',
    overlay: 'rgba(0,0,0,0.5)',
};

export const FILTER_CATEGORIES = [
    "All",
    "Gaming",
    "Music",
    "Live",
    "Mixes",
    "React Native",
    "Programming",
    "Movies",
    "News",
    "Sports",
    "Learning",
    "Fashion",
];

export const MOCK_VIDEOS = [
    {
        id: '1',
        title: 'Building a YouTube Clone in React Native',
        thumbnail: 'https://img.youtube.com/vi/yL_9kU1uC4I/maxresdefault.jpg',
        channel: 'Code Masters',
        channelAvatar: 'https://ui-avatars.com/api/?name=Code+Masters&background=random',
        views: '1.2M',
        time: '2 days ago',
        duration: '10:05',
        url: 'https://www.youtube.com/watch?v=yL_9kU1uC4I',
    },
    {
        id: '2',
        title: 'Top 10 Programming Languages for 2024',
        thumbnail: 'https://img.youtube.com/vi/SfKbQoD7cRw/maxresdefault.jpg',
        channel: 'Tech Trends',
        channelAvatar: 'https://ui-avatars.com/api/?name=Tech+Trends&background=random',
        views: '850K',
        time: '1 week ago',
        duration: '15:30',
        url: 'https://www.youtube.com/watch?v=SfKbQoD7cRw',
    },
    {
        id: '3',
        title: 'React Native Crash Course for Beginners',
        thumbnail: 'https://img.youtube.com/vi/gvkqT_Uoahw/maxresdefault.jpg',
        channel: 'Dev Ed',
        channelAvatar: 'https://ui-avatars.com/api/?name=Dev+Ed&background=random',
        views: '2.5M',
        time: '3 months ago',
        duration: '45:20',
        url: 'https://www.youtube.com/watch?v=gvkqT_Uoahw',
    },
    {
        id: '4',
        title: 'Learn JavaScript in 1 Hour',
        thumbnail: 'https://img.youtube.com/vi/W6NZfCO5SIk/maxresdefault.jpg',
        channel: 'Programming with Mosh',
        channelAvatar: 'https://ui-avatars.com/api/?name=Mosh&background=random',
        views: '5M',
        time: '1 year ago',
        duration: '1:00:00',
        url: 'https://www.youtube.com/watch?v=W6NZfCO5SIk',
    },
    {
        id: '5',
        title: 'CSS Grid vs Flexbox - Which one to use?',
        thumbnail: 'https://img.youtube.com/vi/hs3piaN4b5I/maxresdefault.jpg',
        channel: 'Kevin Powell',
        channelAvatar: 'https://ui-avatars.com/api/?name=Kevin+Powell&background=random',
        views: '300K',
        time: '5 days ago',
        duration: '12:45',
        url: 'https://www.youtube.com/watch?v=hs3piaN4b5I',
    },
    {
        id: '6',
        title: 'Sci-Fi Movie 2024 - Full Movie',
        thumbnail: 'https://img.youtube.com/vi/placeholder1/maxresdefault.jpg',
        channel: 'Movie Central',
        channelAvatar: 'https://ui-avatars.com/api/?name=Movie+Central&background=random',
        views: '5.2M',
        time: '1 month ago',
        duration: '1:45:20',
        url: 'https://www.youtube.com/watch?v=placeholder1',
    },
    {
        id: '7',
        title: 'Action Hero - Full Action Movie',
        thumbnail: 'https://img.youtube.com/vi/placeholder2/maxresdefault.jpg',
        channel: 'Action Movies',
        channelAvatar: 'https://ui-avatars.com/api/?name=Action+Movies&background=random',
        views: '2.1M',
        time: '3 weeks ago',
        duration: '2:10:00',
        url: 'https://www.youtube.com/watch?v=placeholder2',
    },
    {
        id: '8',
        title: 'Adventure Time - Full Movie HD',
        thumbnail: 'https://img.youtube.com/vi/placeholder3/maxresdefault.jpg',
        channel: 'Family Movies',
        channelAvatar: 'https://ui-avatars.com/api/?name=Family+Movies&background=random',
        views: '8.5M',
        time: '1 year ago',
        duration: '1:30:00',
        url: 'https://www.youtube.com/watch?v=placeholder3',
    },
    {
        id: '9',
        title: 'Top 50 Songs of 2024 - Non Stop Music',
        thumbnail: 'https://img.youtube.com/vi/placeholder4/maxresdefault.jpg',
        channel: 'Music Hits',
        channelAvatar: 'https://ui-avatars.com/api/?name=Music+Hits&background=random',
        views: '10M',
        time: '2 months ago',
        duration: '1:10:00',
        url: 'https://www.youtube.com/watch?v=placeholder4',
    },
    {
        id: '10',
        title: 'Chill Vibes - LoFi Hip Hop Mix - Song for Study',
        thumbnail: 'https://img.youtube.com/vi/placeholder5/maxresdefault.jpg',
        channel: 'Lofi Girl',
        channelAvatar: 'https://ui-avatars.com/api/?name=Lofi+Girl&background=random',
        views: '45M',
        time: '1 day ago',
        duration: '24/7',
        url: 'https://www.youtube.com/watch?v=placeholder5',
    },
    {
        id: '11',
        title: 'New Pop Song 2025 (Official Lyric Video)',
        thumbnail: 'https://img.youtube.com/vi/placeholder6/maxresdefault.jpg',
        channel: 'Pop Star',
        channelAvatar: 'https://ui-avatars.com/api/?name=Pop+Star&background=random',
        views: '3.2M',
        time: '5 days ago',
        duration: '3:45',
        url: 'https://www.youtube.com/watch?v=placeholder6',
    },
    {
        id: '12',
        title: 'Funny Cartoon - Tom & Jerry Full Episode',
        thumbnail: 'https://img.youtube.com/vi/placeholder7/maxresdefault.jpg',
        channel: 'Kids TV',
        channelAvatar: 'https://ui-avatars.com/api/?name=Kids+TV&background=random',
        views: '50M',
        time: '3 years ago',
        duration: '10:00',
        url: 'https://www.youtube.com/watch?v=placeholder7',
    },
    {
        id: '13',
        title: 'SpongeBob SquarePants - Best Moments',
        thumbnail: 'https://img.youtube.com/vi/placeholder8/maxresdefault.jpg',
        channel: 'Nickelodeon',
        channelAvatar: 'https://ui-avatars.com/api/?name=Nick&background=random',
        views: '12M',
        time: '6 months ago',
        duration: '15:00',
        url: 'https://www.youtube.com/watch?v=placeholder8',
    },
    {
        id: '14',
        title: 'Peppa Pig - New Episodes',
        thumbnail: 'https://img.youtube.com/vi/placeholder9/maxresdefault.jpg',
        channel: 'Peppa Pig Official',
        channelAvatar: 'https://ui-avatars.com/api/?name=Peppa+Pig&background=random',
        views: '100M',
        time: '1 week ago',
        duration: '20:00',
        url: 'https://www.youtube.com/watch?v=placeholder9',
    },
];
